### PR TITLE
Reflect autoversioning state in HTML UI

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3446

# What does this Pull Request do?
If autoversioning is enabled (as it is by default) then the "Create Version" button is replaced by the text "Autoversioning is enabled. Versions are created with each update to a resource." 

Versioning of binaries is still disabled from the HTML UI, though as binary and binary description versioning is now tied together we might be able to enable this.

Also includes a little CSS change as long binary checksum were breaking the HTML.
Screen Shot 2020-10-14 at 11 13 24 AM

# How should this be tested?

Build this branch and run it. Make a container and see the new message.
Stop Fedora
Run again with `-Dfcrepo.autoversioning.enabled=false` and see the same object show the "Create Version" button.

The button **only** creates a version if something has changed. We will need to make sure this is clear to users of the HTML UI.

# Interested parties
@fcrepo/committers

### CODE REVIEW

**Review by pwinckles — DISMISSED** [review]
Works. A couple of notes:

1. The UI caches that autoversioning is enabled, so it takes some hard refreshes to show otherwise after changing the settings. This is annoying, but the caching is a bigger problem when it does not show newly added children without a hard refresh.
2. The "delete version" button still exists, which is currently not a feature that will be supported in F6.

**Comment by whikloj** [comment]
When you say "change settings" you mean stopping the server and restarting it correct?

**Comment by pwinckles** [comment]
> 
> 
> When you say "change settings" you mean stopping the server and restarting it correct?

Yeah. I don't think you need to do anything about it here.

**Comment by whikloj** [comment]
Yeah, nothing that can be done. Some browsers (<ahem> Chrome) are much more vigilant at using the browser cache. A shift-refresh should force them to check the server again. I've removed the Delete button though

**Review by pwinckles — APPROVED** [review]

**Pull request merged**
