### PR TITLE
FCREPO-3661 - External binaries transmission fixity failures for v5.x

### PR DESCRIPTION
**Pull request by bbpennel**
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3661

# What does this Pull Request do?
* Adds a test to demonstrate a concurrency issue with external binaries in Fedora 5.x
* Fixes that bug
* Switches to using github actions for CI in Fedora 5.

# How should this be tested?
I've added an integration test, but the same issue can be reproduced by starting a bunch of curl requests at once to create external binaries with transmission digests.

### CODE REVIEW

**Review by dbernstein — APPROVED** [review]
👏 👏 👏 👏 👏 👏 👏 👏  Nice work.

**Review by dbernstein — CHANGES_REQUESTED** [review]
@bbpennel : I'm not sure if this is something we need to worry about but the tests don't pass when I run with java 11.0.5 on OSX Catalina (10.15.6).

I'm seeing a couple of issues:

```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.039 s <<< FAILURE! - in org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest
[ERROR] unnecessary Mockito stubbings(org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest)  Time elapsed: 0.039 s  <<< ERROR!
org.mockito.exceptions.misusing.UnnecessaryStubbingException:

Unnecessary stubbings detected in test class: OneToOneTest
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:59)
  2. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:60)
  3. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:61)
  4. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:62)
  5. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:63)
  6. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:64)
  7. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:65)
  8. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:66)
  9. -> at org.fcrepo.kernel.modeshape.observer.eventmappings.OneToOneTest.setUp(OneToOneTest.java:67)
Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.

```

Also it hangs on UrlBinaryTest.   It could be a local issue.  Everything passes when I run on java8.

We're you able to successfully run all the tests on java 11?

**Comment by bbpennel** [comment]
@dbernstein For me, I was able to build with Java 11, but tests don't pass. The tests did not pass in Java 11 prior to this PR as well, the old travis build was setup to allow the java 11 build to fail. I currently have GH actions build but not test under java 11, but @whikloj and I discussed this some yesterday and were leaning towards removing the java 11 build since this version of Fedora only supports java 8 and there's already a version of Fedora that requires java 11. Does that seem reasonable to you?

**Comment by dbernstein** [comment]
@bbpennel :  yes - removing java 11 from github actions seems like the way to go.

**Review by dbernstein — APPROVED** [review]

**Pull request merged**
