### PR TITLE
Add ocfl verify inventory prop

### PR DESCRIPTION
**Pull request by mikejritter**
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3823

# What does this Pull Request do?

* Add prop for setting verify inventory flag for ocfl

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

### CODE REVIEW

**Review by dbernstein — APPROVED** [review]

**Comment by mikejritter** [comment]
A question for something I just looked at: do we want to skip object validation entirely as well if this flag is set? Currently the ObjectValidator in the ReindexSerivce would still run as it uses a separate flag that only impacts if file digests are run (`fcrepo.rebuild.validation.fixity`).

**Comment by dbernstein** [comment]
@mikejritter :  I think so, no?  So if I'm understanding it, the user would have 2 options for rebuild:
1. all validation on (slowest, but high certainty)
2. fixity off but other object validations on (faster, less certainty)
3. all validations off (fastest, but least amount of certainty).
Is that your understanding?  If so I think we should have the option to completely disable all validations in the rebuild.

Perhaps we should be adding a new flag that applies just to the rebuild: 
fcrepo.rebuild.validation.enabled=(true|false) default = true

So that way you can disable validation after rebuild or just disable for the rebuild and leave everything validating.   I'm not sure how this ticket came to be.  I don't recall how it came up.  Apparently I created the ticket.

**Comment by mikejritter** [comment]
> @mikejritter : I think so, no? So if I'm understanding it, the user would have 3 options for rebuild:
> 
>     1. all validation on (slowest, but high certainty)
> 
>     2. fixity off but other object validations on (faster, less certainty)
> 
>     3. all validations off (fastest, but least amount of certainty).
>        Is that your understanding?  If so I think we should have the option to completely disable all validations in the rebuild.

That's what it seems like to me, at least from looking at the ticket.
 
> Perhaps we should be adding a new flag that applies just to the rebuild: fcrepo.rebuild.validation=(true|false) default = true
> 
> So that way you can disable validation after rebuild or just disable for the rebuild and leave everything validating. I'm not sure how this ticket came to be. I don't recall how it came up. Apparently I created the ticket.
> 
> If fcrepo.rebuild.validation=false, but fcrepo.rebuild.validation.fixity=true we should report an exception and shutdown, I would think. Or if fcrepo.rebuild.validation=false then fcrepo.rebuild.validation.fixity would be ignored? What do you think is clearer?

I think an exception would make sense there, just in case one was set incorrectly by mistake.

**Review by dbernstein — APPROVED** [review]

**Comment by dbernstein** [comment]
Just waiting on fix to broken tests with the latest update.

**Pull request merged**
