### PR TITLE
FCREPO-3949 - Reindexing IndirectContainers

### PR DESCRIPTION
**Pull request by bbpennel**
**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3949

# What does this Pull Request do?
Add integration test for rebuilding a repository containing Direct and Indirect containers from OCFL. Update to ReindexingService so that it will reindex both types of containers

# How should this be tested?

Via the integration test, or by deleting the database of a fcrepo 6 repository which containers IndirectContainers and then rebuilding the index.

# Interested parties

### CODE REVIEW

**Comment by Surfrdan** [comment]
I'm getting the same test failures at home as the automated builds here. 

```
[ERROR] Failures:
[ERROR]   ReindexServiceTest.rebuildRepoLotsOfMembership:357
membershipService.populateMembershipHistory(
    <any org.fcrepo.kernel.api.Transaction>,
    <any org.fcrepo.kernel.api.identifiers.FedoraId>
);
Wanted 18 times:
-> at org.fcrepo.persistence.ocfl.impl.ReindexServiceTest.rebuildRepoLotsOfMembership(ReindexServiceTest.java:357)
But was 36 times:
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.lambda$indexContainerType$4(ReindexService.java:253)


[ERROR]   ReindexServiceTest.testRebuildOnce:144
searchIndex.doSearch(
    <any org.fcrepo.search.api.SearchParameters>
);
Wanted 1 time:
-> at org.fcrepo.persistence.ocfl.impl.ReindexServiceTest.testRebuildOnce(ReindexServiceTest.java:144)
But was 2 times:
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.indexContainerType(ReindexService.java:247)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.indexContainerType(ReindexService.java:247)


[ERROR]   ReindexServiceTest.testRebuildWithContinue:216
searchIndex.doSearch(
    <any org.fcrepo.search.api.SearchParameters>
);
Wanted 1 time:
-> at org.fcrepo.persistence.ocfl.impl.ReindexServiceTest.testRebuildWithContinue(ReindexServiceTest.java:216)
But was 2 times:
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.indexContainerType(ReindexService.java:247)
-> at org.fcrepo.persistence.ocfl.impl.ReindexService.indexContainerType(ReindexService.java:247)


[INFO]
[ERROR] Tests run: 68, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by bbpennel** [comment]
@Surfrdan Sorry that should be resolved now. The number of searches and membership indexing calls from ReindexingService doubles in this PR since it is checking for both Direct and Indirect containers, and I forgot to update the unit test accordingly.

**Comment by Surfrdan** [comment]
Looks good to me. Tested the use case from David Novak which highlighted this in the first instance and the membership table is now populated after a reindex. There is a question around the handling of ACLs within reindexing which I have asked about on Slack, but this particular PR can be merged I believe.

**Comment by motyc** [comment]
Thank you all for solving that issue!

**Pull request merged**
