### PR TITLE
Change how we configure the HikariCP

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3903

# What does this Pull Request do?
This alters how we configure the HikariCP to allow inserting a separate file of configuration properties.

Instead of needing us to expose all the various [configuration](https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby) from HikariCP, this allows users to tweak any configuration knobs on their own...for better or worse.

# How should this be tested?

I'm suggesting this as an alternative to #2043 so I would suggest using the same method with a slight tweak.

Setup and then stop a mysql container.
```sh
> docker run --name fcrepo-database -e MYSQL_ROOT_PASSWORD=root-pw -e MYSQL_DATABASE=fcrepo -e MYSQL_USER=fcrepo-user -e MYSQL_PASSWORD=fcrepo-pw -p 3306:3306 -d mysql:8.0
> docker container stop fcrepo-database
```

Create an empty text file (i.e. `hikari.props`)
Then start Fedora with the new `fcrepo.db.custom.properties` property set with the absolute path to the above text file.

For example:
```sh
> mvn -Dfcrepo.db.custom.properties=/Users/jaredwhiklo/www/fcrepo4/testing_helper/config_files/hikari.props -Dfcrepo.log=DEBUG -Dfcrepo.db.url=jdbc:mysql://localhost:3306/fcrepo -Dfcrepo.db.user=fcrepo-user -Dfcrepo.db.password=fcrepo-pw -Dfcrepo.home=/Users/jaredwhiklo/www/fcrepo4/ocfl_temp jetty:run -pl fcrepo-webapp
```
You'll see (something like)
```
INFO 15:48:27.732 [main] (OcflPropsConfig) Fedora OCFL digest algorithm: SHA-512
INFO 15:48:27.751 [main] (DatabaseConfig) JDBC URL: jdbc:mysql://localhost:3306/fcrepo
INFO 15:48:27.751 [main] (DatabaseConfig) JDBC User: fcrepo-user
INFO 15:48:27.751 [main] (DatabaseConfig) JDBC Password length: 9
INFO 15:48:27.751 [main] (DatabaseConfig) Using database driver: com.mysql.cj.jdbc.Driver
INFO 15:48:27.753 [main] (DatabaseConfig) Using an external configuration file for Hikari: /Users/jaredwhiklo/www/fcrepo4/testing_helper/config_files/hikari.props
ERROR 15:48:28.836 [main] (HikariPool) HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```
and then stacktraces.

If you `Ctrl-C` to stop the Fedora and edit the hikari.props file and add a line
`initializationFailTimeout=0` or `initializationFailTimeout=-1` and start Fedora again with the same command as above

It should stop initializing and hang at
```
INFO 08:40:26.155 [main] (OcflPropsConfig) Fedora OCFL digest algorithm: SHA-512
INFO 08:40:26.176 [main] (DatabaseConfig) JDBC URL: jdbc:mysql://localhost:3306/fcrepo
INFO 08:40:26.176 [main] (DatabaseConfig) JDBC User: fcrepo-user
INFO 08:40:26.176 [main] (DatabaseConfig) JDBC Password length: 9
INFO 08:40:26.176 [main] (DatabaseConfig) Using database driver: com.mysql.cj.jdbc.Driver
INFO 08:40:26.180 [main] (DatabaseConfig) Using an external configuration file for Hikari: /Users/jaredwhiklo/www/fcrepo4/testing_helper/config_files/hikari.props
DEBUG 08:40:26.203 [main] (DatabaseConfig) Instantiating a new flyway bean
```
Fedora will wait for 30 seconds by default, you can adjust this with the HikariCP `connectionTimeout` setting or `fcrepo.db.connection.checkout.timeout` setting.

Without exiting (i.e. another terminal/window) restart the database container
```sh
> docker container start fcrepo-database
```
The application should then continue to start up.
```
INFO 09:42:18.222 [main] (OcflPropsConfig) Fedora OCFL digest algorithm: SHA-512
INFO 09:42:18.242 [main] (DatabaseConfig) JDBC URL: jdbc:mysql://localhost:3306/fcrepo
INFO 09:42:18.242 [main] (DatabaseConfig) JDBC User: fcrepo-user
INFO 09:42:18.242 [main] (DatabaseConfig) JDBC Password length: 9
INFO 09:42:18.242 [main] (DatabaseConfig) Using database driver: com.mysql.cj.jdbc.Driver
INFO 09:42:18.245 [main] (DatabaseConfig) Using an external configuration file for Hikari: /Users/jaredwhiklo/www/fcrepo4/testing_helper/config_files/hikari.props
DEBUG 09:42:19.328 [main] (DatabaseConfig) Instantiating a new flyway bean
DEBUG 09:42:29.932 [main] (DbPlatform) Identified database as: MySQL
DEBUG 09:42:29.940 [main] (DbPlatform) Identified database as: MySQL
DEBUG 09:42:29.944 [main] (DbPlatform) Identified database as: MySQL
DEBUG 09:42:29.951 [main] (WebappConfig) Event bus threads: org.fcrepo.config.FedoraPropsConfig$$EnhancerBySpringCGLIB$$f87ee774@2ce80c85
DEBUG 09:42:29.965 [main] (DbPlatform) Identified database as: MySQL
INFO 09:42:29.999 [main] (JmsConfig) JMS messaging enabled
```

**Note**: If you use the old `fcrepo.db.connection.checkout.timeout` or `fcrepo.db.max.pool.size` properties they will override the associated HikariCP properties (`connectionTimeout` and  `maximumPoolSize`). If you set the aforementioned HikariCP properties in the properties file you will see a logged warning on start up like.

For example: With the line `connectionTimeout=40000` in your `hikari.props` file, then including `-Dfcrepo.db.connection.checkout.timeout=20000` in your JAVA OPTs or CATALINA OPTs you will see a warning in the startup logs. 

```
INFO 09:53:13.526 [main] (OcflPropsConfig) Fedora OCFL digest algorithm: SHA-512
INFO 09:53:13.546 [main] (DatabaseConfig) JDBC URL: jdbc:mysql://localhost:3306/ispn
INFO 09:53:13.546 [main] (DatabaseConfig) JDBC User: fcrepo-user
INFO 09:53:13.546 [main] (DatabaseConfig) JDBC Password length: 9
INFO 09:53:13.546 [main] (DatabaseConfig) Using database driver: com.mysql.cj.jdbc.Driver
INFO 09:53:13.549 [main] (DatabaseConfig) Using an external configuration file for Hikari: /Users/jaredwhiklo/www/fcrepo4/testing_helper/config_files/hikari.props
WARN 09:53:13.549 [main] (DatabaseConfig) Overriding HikariCP connectionTimeout setting in file from 40000 to 20000 
DEBUG 09:53:13.738 [main] (DatabaseConfig) Instantiating a new flyway bean
```

# Interested parties

Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @whikloj! I could live with either of these approaches, but this one does seem potentially more flexible and easier to maintain (especially if there's a need to override more/other Hikari properties).

**Review by mikejritter — APPROVED** [review]
Works as expected :+1:

**Comment by mikejritter** [comment]
@whikloj I meant to ask, do we want to have an discussion on this vs #2043? Personally I would prefer this PR as we wouldn't need to worry about mapping the properties to hikari. I wanted to get a feel for what others wanted before just merging though.

**Comment by whikloj** [comment]
Yeah, I didn't just want to decide on my own either.

Really what I'm wondering about is if we should remove the existing
properties for connection timeout and max pool size (after some
depreciation cycle).

So if you want to merge this I agree it seems a better choice then #2043.

We can table a discussion on the existing properties till the next call.

**Pull request merged**
